//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityPicturePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivityPicturePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Import.
        /// </summary>
        internal static string ActionImport_Text {
            get {
                return ResourceManager.GetString("ActionImport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Pictures.
        /// </summary>
        internal static string ActivityPicturePage_Title {
            get {
                return ResourceManager.GetString("ActivityPicturePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Picture Plugin.
        /// </summary>
        internal static string ActivityPicturePlugin_Text {
            get {
                return ResourceManager.GetString("ActivityPicturePlugin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto import from checked folders.
        /// </summary>
        internal static string AutoImportFromFolders_Text {
            get {
                return ResourceManager.GetString("AutoImportFromFolders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string btnCollapseAll_Text {
            get {
                return ResourceManager.GetString("btnCollapseAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string btnExpandAll_Text {
            get {
                return ResourceManager.GetString("btnExpandAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geotag.
        /// </summary>
        internal static string btnGeoTag_Text {
            get {
                return ResourceManager.GetString("btnGeoTag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnimage {
            get {
                object obj = ResourceManager.GetObject("btnimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Google Earth.
        /// </summary>
        internal static string btnKML_Text {
            get {
                return ResourceManager.GetString("btnKML_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time offset.
        /// </summary>
        internal static string btnTimeOffset_Text {
            get {
                return ResourceManager.GetString("btnTimeOffset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnvideo {
            get {
                object obj = ResourceManager.GetObject("btnvideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Camera {
            get {
                object obj = ResourceManager.GetObject("Camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change file listview.
        /// </summary>
        internal static string ChangeFileListview_Text {
            get {
                return ResourceManager.GetString("ChangeFileListview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change image listview.
        /// </summary>
        internal static string ChangeImageListview_Text {
            get {
                return ResourceManager.GetString("ChangeImageListview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for duplicate images and videos. {0} of {1} checked..
        /// </summary>
        internal static string CheckingForDuplicates_Text {
            get {
                return ResourceManager.GetString("CheckingForDuplicates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string commentDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("commentDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected items?.
        /// </summary>
        internal static string ConfirmDeleteLong_Text {
            get {
                return ResourceManager.GetString("ConfirmDeleteLong_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDeleteShort_Text {
            get {
                return ResourceManager.GetString("ConfirmDeleteShort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created with {0} for SportTracks.
        /// </summary>
        internal static string CreatedWithXForSportTracks_Text {
            get {
                return ResourceManager.GetString("CreatedWithXForSportTracks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Destination_Text {
            get {
                return ResourceManager.GetString("Destination_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Model.
        /// </summary>
        internal static string equipmentModelDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("equipmentModelDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound_Text {
            get {
                return ResourceManager.GetString("FileNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string FilePath_Text {
            get {
                return ResourceManager.GetString("FilePath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Images To View.
        /// </summary>
        internal static string FitImagesToView_Text {
            get {
                return ResourceManager.GetString("FitImagesToView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} images or videos in activity..
        /// </summary>
        internal static string FoundImagesInActivity_Text {
            get {
                return ResourceManager.GetString("FoundImagesInActivity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} images or videos in folder..
        /// </summary>
        internal static string FoundImagesInFolder_Text {
            get {
                return ResourceManager.GetString("FoundImagesInFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0} activities.
        /// </summary>
        internal static string FromXActivities_Text {
            get {
                return ResourceManager.GetString("FromXActivities_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GE {
            get {
                object obj = ResourceManager.GetObject("GE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GE2 {
            get {
                object obj = ResourceManager.GetObject("GE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos to Google Earth.
        /// </summary>
        internal static string GoogleEarthExport_Title {
            get {
                return ResourceManager.GetString("GoogleEarthExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options (for selected photos).
        /// </summary>
        internal static string goupBoxListOptions_Text {
            get {
                return ResourceManager.GetString("goupBoxListOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string groupBoxVideo_Text {
            get {
                return ResourceManager.GetString("groupBoxVideo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide All Columns.
        /// </summary>
        internal static string HideAllColumns_Text {
            get {
                return ResourceManager.GetString("HideAllColumns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding file.
        /// </summary>
        internal static string ImportControl_addingFile {
            get {
                return ResourceManager.GetString("ImportControl_addingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change View.
        /// </summary>
        internal static string ImportControl_changeView {
            get {
                return ResourceManager.GetString("ImportControl_changeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Photo.
        /// </summary>
        internal static string ImportControl_importing {
            get {
                return ResourceManager.GetString("ImportControl_importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string ImportControl_in {
            get {
                return ResourceManager.GetString("ImportControl_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan done: A total of {0} new photos have been found.
        /// </summary>
        internal static string ImportControl_scanDone {
            get {
                return ResourceManager.GetString("ImportControl_scanDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning of.
        /// </summary>
        internal static string ImportControl_scanning {
            get {
                return ResourceManager.GetString("ImportControl_scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching matching activity for.
        /// </summary>
        internal static string ImportControl_searchingActivity {
            get {
                return ResourceManager.GetString("ImportControl_searchingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string labelDay_Text {
            get {
                return ResourceManager.GetString("labelDay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string labelImageSize_Text {
            get {
                return ResourceManager.GetString("labelImageSize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string labelMinute_Text {
            get {
                return ResourceManager.GetString("labelMinute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string labelSecond_Text {
            get {
                return ResourceManager.GetString("labelSecond_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MigratePaths....
        /// </summary>
        internal static string MigratePaths_Text {
            get {
                return ResourceManager.GetString("MigratePaths_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate Source Path.
        /// </summary>
        internal static string MigrateSourcePath_Text {
            get {
                return ResourceManager.GetString("MigrateSourcePath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time Stamp.
        /// </summary>
        internal static string ModifyTimeStamp_Text {
            get {
                return ResourceManager.GetString("ModifyTimeStamp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder.
        /// </summary>
        internal static string OpenContainingFolder_Text {
            get {
                return ResourceManager.GetString("OpenContainingFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Google Earth when created.
        /// </summary>
        internal static string OpenInGoogleEarthWhenCreated_Text {
            get {
                return ResourceManager.GetString("OpenInGoogleEarthWhenCreated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Source.
        /// </summary>
        internal static string photoSourceDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("photoSourceDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string pictureAlbumToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pictureAlbumToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceID.
        /// </summary>
        internal static string referenceIDDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("referenceIDDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list?.
        /// </summary>
        internal static string RemoveFromList_Text {
            get {
                return ResourceManager.GetString("RemoveFromList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Snapshot.
        /// </summary>
        internal static string ResetSnapshot_Text {
            get {
                return ResourceManager.GetString("ResetSnapshot_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string SelectFolder_Text {
            get {
                return ResourceManager.GetString("SelectFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string SettingsPageControl_lblQuality_Text {
            get {
                return ResourceManager.GetString("SettingsPageControl_lblQuality_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Columns.
        /// </summary>
        internal static string ShowAllColumns_Text {
            get {
                return ResourceManager.GetString("ShowAllColumns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting {0} images.
        /// </summary>
        internal static string SortingXImages {
            get {
                return ResourceManager.GetString("SortingXImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting {0} of {1} images.
        /// </summary>
        internal static string SortingXofYImages {
            get {
                return ResourceManager.GetString("SortingXofYImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source_Text {
            get {
                return ResourceManager.GetString("Source_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportTracks images exported with.
        /// </summary>
        internal static string SportTracksImagesExportedWith_Text {
            get {
                return ResourceManager.GetString("SportTracksImagesExportedWith_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store kmz/kml file locations.
        /// </summary>
        internal static string StoreGEFileLocations_Text {
            get {
                return ResourceManager.GetString("StoreGEFileLocations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string thumbnailDataGridViewImageColumn_HeaderText {
            get {
                return ResourceManager.GetString("thumbnailDataGridViewImageColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string titleDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("titleDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string toolStripButtonPause_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonPause_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string toolStripButtonPlay_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonPlay_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        internal static string toolStripButtonSnapshot_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonSnapshot_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string toolStripButtonStop_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonStop_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected photos.
        /// </summary>
        internal static string tooltip_OnlySelectedImages {
            get {
                return ResourceManager.GetString("tooltip_OnlySelectedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeImage_HeaderText {
            get {
                return ResourceManager.GetString("TypeImage_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint.
        /// </summary>
        internal static string waypointDataGridViewTextBoxColumn_HeaderText {
            get {
                return ResourceManager.GetString("waypointDataGridViewTextBoxColumn_HeaderText", resourceCulture);
            }
        }
    }
}
